# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17',
          cache: 'gradle'


      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}

      - name: test 
        run: flutter test

      - name: build
        run: |
          flutter pub get
          flutter build apk --release --split-per-abi
          flutter build appbundle
    
