# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:


jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
        channel: 'stable'
    - name: test 
      run: flutter test
    - name: build
      run: flutter pub get
      run: flutter build apk --release --split-per-abi
      run: flutter build appbundle
