# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v3.2.0-beta.1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-3.0.5
      
      - if: ${{ steps.cache-flutter.outputs.cache-hit != 'true' }}
        name: List the state of flutter
        continue-on-error: true
        run: echo "cache not found"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - name: test 
        run: flutter test
      - name: build
        run: |
          flutter pub get
          flutter build apk --release --split-per-abi
          flutter build appbundle
    
